//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.17 at 05:31:15 PM CET 
//


package com.rapidminer.operator.modelling.configuration.xsd.optionalparameterspecification;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rapidminer.operator.modelling.configuration.xsd.optionalparameterspecification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rapidminer.operator.modelling.configuration.xsd.optionalparameterspecification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OptionalParameter }
     * 
     */
    public OptionalParameter createOptionalParameter() {
        return new OptionalParameter();
    }

    /**
     * Create an instance of {@link OptionalParameter.ParameterConditions }
     * 
     */
    public OptionalParameter.ParameterConditions createOptionalParameterParameterConditions() {
        return new OptionalParameter.ParameterConditions();
    }

    /**
     * Create an instance of {@link OptionalParameter.Categories }
     * 
     */
    public OptionalParameter.Categories createOptionalParameterCategories() {
        return new OptionalParameter.Categories();
    }

    /**
     * Create an instance of {@link OptionalParameter.MlnEngines }
     * 
     */
    public OptionalParameter.MlnEngines createOptionalParameterMlnEngines() {
        return new OptionalParameter.MlnEngines();
    }

    /**
     * Create an instance of {@link OptionalParameters }
     * 
     */
    public OptionalParameters createOptionalParameters() {
        return new OptionalParameters();
    }

    /**
     * Create an instance of {@link OptionalParameter.ParameterConditions.ParameterCondition }
     * 
     */
    public OptionalParameter.ParameterConditions.ParameterCondition createOptionalParameterParameterConditionsParameterCondition() {
        return new OptionalParameter.ParameterConditions.ParameterCondition();
    }

    /**
     * Create an instance of {@link OptionalParameter.Categories.Category }
     * 
     */
    public OptionalParameter.Categories.Category createOptionalParameterCategoriesCategory() {
        return new OptionalParameter.Categories.Category();
    }

    /**
     * Create an instance of {@link OptionalParameter.MlnEngines.MlnEngine }
     * 
     */
    public OptionalParameter.MlnEngines.MlnEngine createOptionalParameterMlnEnginesMlnEngine() {
        return new OptionalParameter.MlnEngines.MlnEngine();
    }

}
