//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.19 at 05:11:47 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xsd.configuration.modelling.operator.rapidminer.com/MLNFileTypeSpecification", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rapidminer.operator.modelling.configuration.xsd.mlnfiletypespecification;
