//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 07:56:39 PM CET 
//


package com.rapidminer.operator.modelling.configuration.xsd.mlnenginespecification;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mlnEngine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mlnEngine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="learningTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="learningType" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="inferenceTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="inferenceType" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="optionalParameters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="optionalParameter" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inferenceAdapter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="learningAdapter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="queryAtomsInRules" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="multipleEvidenceFilesInference" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="multipleEvidenceFilesLearning" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="variableWeights" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Learning"/>
 *             &lt;enumeration value="Inference"/>
 *             &lt;enumeration value="Both"/>
 *             &lt;enumeration value="Neither"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="plusNotation" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="exclConstraintConversion" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mlnEngine", propOrder = {
    "learningTypes",
    "inferenceTypes",
    "optionalParameters"
})
public class MlnEngine {

    protected MlnEngine.LearningTypes learningTypes;
    protected MlnEngine.InferenceTypes inferenceTypes;
    protected MlnEngine.OptionalParameters optionalParameters;
    @XmlAttribute(name = "key", required = true)
    protected String key;
    @XmlAttribute(name = "fileType", required = true)
    protected String fileType;
    @XmlAttribute(name = "inferenceAdapter", required = true)
    protected String inferenceAdapter;
    @XmlAttribute(name = "learningAdapter", required = true)
    protected String learningAdapter;
    @XmlAttribute(name = "queryAtomsInRules", required = true)
    protected boolean queryAtomsInRules;
    @XmlAttribute(name = "multipleEvidenceFilesInference", required = true)
    protected boolean multipleEvidenceFilesInference;
    @XmlAttribute(name = "multipleEvidenceFilesLearning", required = true)
    protected boolean multipleEvidenceFilesLearning;
    @XmlAttribute(name = "variableWeights", required = true)
    protected String variableWeights;
    @XmlAttribute(name = "plusNotation", required = true)
    protected boolean plusNotation;
    @XmlAttribute(name = "exclConstraintConversion", required = true)
    protected boolean exclConstraintConversion;

    /**
     * Gets the value of the learningTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MlnEngine.LearningTypes }
     *     
     */
    public MlnEngine.LearningTypes getLearningTypes() {
        return learningTypes;
    }

    /**
     * Sets the value of the learningTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MlnEngine.LearningTypes }
     *     
     */
    public void setLearningTypes(MlnEngine.LearningTypes value) {
        this.learningTypes = value;
    }

    /**
     * Gets the value of the inferenceTypes property.
     * 
     * @return
     *     possible object is
     *     {@link MlnEngine.InferenceTypes }
     *     
     */
    public MlnEngine.InferenceTypes getInferenceTypes() {
        return inferenceTypes;
    }

    /**
     * Sets the value of the inferenceTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MlnEngine.InferenceTypes }
     *     
     */
    public void setInferenceTypes(MlnEngine.InferenceTypes value) {
        this.inferenceTypes = value;
    }

    /**
     * Gets the value of the optionalParameters property.
     * 
     * @return
     *     possible object is
     *     {@link MlnEngine.OptionalParameters }
     *     
     */
    public MlnEngine.OptionalParameters getOptionalParameters() {
        return optionalParameters;
    }

    /**
     * Sets the value of the optionalParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link MlnEngine.OptionalParameters }
     *     
     */
    public void setOptionalParameters(MlnEngine.OptionalParameters value) {
        this.optionalParameters = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the fileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * Sets the value of the fileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileType(String value) {
        this.fileType = value;
    }

    /**
     * Gets the value of the inferenceAdapter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInferenceAdapter() {
        return inferenceAdapter;
    }

    /**
     * Sets the value of the inferenceAdapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInferenceAdapter(String value) {
        this.inferenceAdapter = value;
    }

    /**
     * Gets the value of the learningAdapter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLearningAdapter() {
        return learningAdapter;
    }

    /**
     * Sets the value of the learningAdapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLearningAdapter(String value) {
        this.learningAdapter = value;
    }

    /**
     * Gets the value of the queryAtomsInRules property.
     * 
     */
    public boolean isQueryAtomsInRules() {
        return queryAtomsInRules;
    }

    /**
     * Sets the value of the queryAtomsInRules property.
     * 
     */
    public void setQueryAtomsInRules(boolean value) {
        this.queryAtomsInRules = value;
    }

    /**
     * Gets the value of the multipleEvidenceFilesInference property.
     * 
     */
    public boolean isMultipleEvidenceFilesInference() {
        return multipleEvidenceFilesInference;
    }

    /**
     * Sets the value of the multipleEvidenceFilesInference property.
     * 
     */
    public void setMultipleEvidenceFilesInference(boolean value) {
        this.multipleEvidenceFilesInference = value;
    }

    /**
     * Gets the value of the multipleEvidenceFilesLearning property.
     * 
     */
    public boolean isMultipleEvidenceFilesLearning() {
        return multipleEvidenceFilesLearning;
    }

    /**
     * Sets the value of the multipleEvidenceFilesLearning property.
     * 
     */
    public void setMultipleEvidenceFilesLearning(boolean value) {
        this.multipleEvidenceFilesLearning = value;
    }

    /**
     * Gets the value of the variableWeights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableWeights() {
        return variableWeights;
    }

    /**
     * Sets the value of the variableWeights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableWeights(String value) {
        this.variableWeights = value;
    }

    /**
     * Gets the value of the plusNotation property.
     * 
     */
    public boolean isPlusNotation() {
        return plusNotation;
    }

    /**
     * Sets the value of the plusNotation property.
     * 
     */
    public void setPlusNotation(boolean value) {
        this.plusNotation = value;
    }

    /**
     * Gets the value of the exclConstraintConversion property.
     * 
     */
    public boolean isExclConstraintConversion() {
        return exclConstraintConversion;
    }

    /**
     * Sets the value of the exclConstraintConversion property.
     * 
     */
    public void setExclConstraintConversion(boolean value) {
        this.exclConstraintConversion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="inferenceType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inferenceType"
    })
    public static class InferenceTypes {

        protected List<MlnEngine.InferenceTypes.InferenceType> inferenceType;

        /**
         * Gets the value of the inferenceType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the inferenceType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInferenceType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MlnEngine.InferenceTypes.InferenceType }
         * 
         * 
         */
        public List<MlnEngine.InferenceTypes.InferenceType> getInferenceType() {
            if (inferenceType == null) {
                inferenceType = new ArrayList<MlnEngine.InferenceTypes.InferenceType>();
            }
            return this.inferenceType;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class InferenceType {

            @XmlAttribute(name = "key")
            protected String key;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="learningType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "learningType"
    })
    public static class LearningTypes {

        protected List<MlnEngine.LearningTypes.LearningType> learningType;

        /**
         * Gets the value of the learningType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the learningType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLearningType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MlnEngine.LearningTypes.LearningType }
         * 
         * 
         */
        public List<MlnEngine.LearningTypes.LearningType> getLearningType() {
            if (learningType == null) {
                learningType = new ArrayList<MlnEngine.LearningTypes.LearningType>();
            }
            return this.learningType;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class LearningType {

            @XmlAttribute(name = "key")
            protected String key;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="optionalParameter" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "optionalParameter"
    })
    public static class OptionalParameters {

        protected List<MlnEngine.OptionalParameters.OptionalParameter> optionalParameter;

        /**
         * Gets the value of the optionalParameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the optionalParameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOptionalParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MlnEngine.OptionalParameters.OptionalParameter }
         * 
         * 
         */
        public List<MlnEngine.OptionalParameters.OptionalParameter> getOptionalParameter() {
            if (optionalParameter == null) {
                optionalParameter = new ArrayList<MlnEngine.OptionalParameters.OptionalParameter>();
            }
            return this.optionalParameter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class OptionalParameter {

            @XmlAttribute(name = "key")
            protected String key;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

        }

    }

}
