//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 07:56:39 PM CET 
//


package com.rapidminer.operator.modelling.configuration.xsd.mlnenginespecification;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rapidminer.operator.modelling.configuration.xsd.mlnenginespecification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rapidminer.operator.modelling.configuration.xsd.mlnenginespecification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MlnEngine }
     * 
     */
    public MlnEngine createMlnEngine() {
        return new MlnEngine();
    }

    /**
     * Create an instance of {@link MlnEngine.OptionalParameters }
     * 
     */
    public MlnEngine.OptionalParameters createMlnEngineOptionalParameters() {
        return new MlnEngine.OptionalParameters();
    }

    /**
     * Create an instance of {@link MlnEngine.InferenceTypes }
     * 
     */
    public MlnEngine.InferenceTypes createMlnEngineInferenceTypes() {
        return new MlnEngine.InferenceTypes();
    }

    /**
     * Create an instance of {@link MlnEngine.LearningTypes }
     * 
     */
    public MlnEngine.LearningTypes createMlnEngineLearningTypes() {
        return new MlnEngine.LearningTypes();
    }

    /**
     * Create an instance of {@link MlnEngines }
     * 
     */
    public MlnEngines createMlnEngines() {
        return new MlnEngines();
    }

    /**
     * Create an instance of {@link MlnEngine.OptionalParameters.OptionalParameter }
     * 
     */
    public MlnEngine.OptionalParameters.OptionalParameter createMlnEngineOptionalParametersOptionalParameter() {
        return new MlnEngine.OptionalParameters.OptionalParameter();
    }

    /**
     * Create an instance of {@link MlnEngine.InferenceTypes.InferenceType }
     * 
     */
    public MlnEngine.InferenceTypes.InferenceType createMlnEngineInferenceTypesInferenceType() {
        return new MlnEngine.InferenceTypes.InferenceType();
    }

    /**
     * Create an instance of {@link MlnEngine.LearningTypes.LearningType }
     * 
     */
    public MlnEngine.LearningTypes.LearningType createMlnEngineLearningTypesLearningType() {
        return new MlnEngine.LearningTypes.LearningType();
    }

}
